language: python

cache:
  directories:
    - $HOME/miniconda3

before_install:
  - . ./scripts/install_miniconda.sh

install:
  - . ./scripts/create_testenv.sh
  - pip install coveralls

script:
  - pytest -v --cov=csrank --ignore experiments

after_success:
  - coveralls
