language: python

cache:
  directories:
    - $HOME/miniconda3

before_install:
  - . ./scripts/install_miniconda.sh

install:
  - . ./scripts/create_testenv.sh
  - conda install --yes sphinx
  - pip install coveralls travis-sphinx nbsphinx sphinx_rtd_theme

script:
  - pytest -v --cov=csrank --ignore experiments
  - travis-sphinx build --source=docs

after_success:
  - coveralls
  - travis-sphinx deploy
