language: python

cache:
  directories:
    - $HOME/miniconda3

addons:
  apt_packages:
    - pandoc

before_install:
  - . ./scripts/install_miniconda.sh

install:
  - . ./scripts/create_testenv.sh
  - conda install --yes sphinx ipython
  - pip install -I travis-sphinx>=2.1.0
  - pip install coveralls nbsphinx sphinx_rtd_theme

script:
  - pytest -v --cov=csrank --ignore experiments
  - travis-sphinx build -n --source=docs

after_success:
  - coveralls
  - travis-sphinx deploy
